<a href="https://colab.research.google.com/github/inputJun/MachineLearning-Study/blob/main/%EA%B3%A0%EC%A4%80%ED%99%98201700846%EB%82%A0%EC%94%A8%ED%8C%90%EB%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**201700846 고준환**

In [103]:
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt

In [104]:
Weather_df= pd.read_csv("TLS-weather-data-2013.csv", error_bad_lines = False)
Weather_df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


CET  Max TemperatureC  Mean TemperatureC  Min TemperatureC  \
0  2013-01-01                12                  9                 6   
1  2013-01-02                 9                  7                 4   
2  2013-01-03                 8                  4                 0   
3  2013-01-04                 7                  6                 5   
4  2013-01-05                 7                  6                 5   

   Dew PointC  MeanDew PointC  Min DewpointC  Max Humidity  Mean Humidity  \
0           8               7              5            93             86   
1           6               4              2            93             86   
2           4               2             -1           100             87   
3           7               6              4           100             94   
4           6               6              4           100             94   

   Min Humidity  ...  Max VisibilityKm  Mean VisibilityKm  Min VisibilitykM  \
0            76  ...                31                 10                 5   
1            71  ...                31                 11                10   
2            69  ...                19                 10                10   
3            83  ...                10                  6                 1   
4            90  ...                11                  9                 2   

   Max Wind SpeedKm/h  Mean Wind SpeedKm/h  Max Gust SpeedKm/h  \
0                  26                   14                 NaN   
1                  23                   16                 NaN   
2                  13                    5                 NaN   
3                  10                    5                 NaN   
4                  16                    8                 NaN   

   Precipitationmm  CloudCover  Events  WindDirDegrees  
0             5.08         7.0    Rain             234  
1             0.00         5.0     NaN             298  
2             0.00         5.0     NaN             118  
3             0.00         8.0     Fog             292  
4             0.00         8.0     NaN             306  

[5 rows x 23 columns]

**TLS-weather-data-2013.csv 파일에 대한 분석**

In [105]:
Weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   CET                         365 non-null    object 
 1   Max TemperatureC            365 non-null    int64  
 2   Mean TemperatureC           365 non-null    int64  
 3   Min TemperatureC            365 non-null    int64  
 4   Dew PointC                  365 non-null    int64  
 5   MeanDew PointC              365 non-null    int64  
 6   Min DewpointC               365 non-null    int64  
 7   Max Humidity                365 non-null    int64  
 8   Mean Humidity               365 non-null    int64  
 9   Min Humidity                365 non-null    int64  
 10  Max Sea Level PressurehPa   365 non-null    int64  
 11  Mean Sea Level PressurehPa  365 non-null    int64  
 12  Min Sea Level PressurehPa   365 non-null    int64  
 13  Max VisibilityKm            365 non

In [106]:
Weather_df.describe()

Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000   
mean          17.769863          13.369863          9.038356   10.690411   
std            8.242990           7.207495          6.569046    5.605143   
min           -1.000000          -2.000000         -7.000000   -6.000000   
25%           12.000000           7.000000          4.000000    6.000000   
50%           18.000000          13.000000          9.000000   10.000000   
75%           24.000000          19.000000         14.000000   15.000000   
max           37.000000          28.000000         22.000000   22.000000   

       MeanDew PointC  Min DewpointC  Max Humidity  Mean Humidity  \
count      365.000000     365.000000    365.000000     365.000000   
mean         8.473973       6.008219     91.994521      73.884932   
std          5.657583       5.797161      6.700826      10.917167   
min         -8.000000     -10.000000     63.000000      47.000000   
25%          4.000000       2.000000     88.000000      67.000000   
50%          8.000000       6.000000     93.000000      75.000000   
75%         13.000000      11.000000     94.000000      82.000000   
max         20.000000      17.000000    100.000000      96.000000   

       Min Humidity  Max Sea Level PressurehPa  ...  \
count    365.000000                 365.000000  ...   
mean      49.701370                1019.895890  ...   
std       16.428203                   7.524328  ...   
min       14.000000                 996.000000  ...   
25%       38.000000                1016.000000  ...   
50%       48.000000                1020.000000  ...   
75%       60.000000                1025.000000  ...   
max       92.000000                1042.000000  ...   

       Min Sea Level PressurehPa  Max VisibilityKm  Mean VisibilityKm  \
count                 365.000000        365.000000         365.000000   
mean                 1014.224658         24.000000           9.975342   
std                     8.707010          7.936216           1.387521   
min                   979.000000          7.000000           2.000000   
25%                  1010.000000         19.000000          10.000000   
50%                  1015.000000         26.000000          10.000000   
75%                  1020.000000         31.000000          11.000000   
max                  1037.000000         31.000000          14.000000   

       Min VisibilitykM  Max Wind SpeedKm/h  Mean Wind SpeedKm/h  \
count        365.000000          365.000000           365.000000   
mean           7.178082           25.945205            13.252055   
std            3.445584            9.329868             6.474975   
min            0.000000            8.000000             3.000000   
25%            5.000000           19.000000             8.000000   
50%           10.000000           26.000000            11.000000   
75%           10.000000           32.000000            18.000000   
max           10.000000           60.000000            50.000000   

       Max Gust SpeedKm/h  Precipitationmm  CloudCover  WindDirDegrees  
count           61.000000       365.000000  358.000000      365.000000  
mean            56.229508         1.186356    5.315642      235.534247  
std             15.584601         3.008979    2.271078       75.526300  
min             27.000000         0.000000    1.000000        1.000000  
25%             48.000000         0.000000    4.000000      156.000000  
50%             52.000000         0.000000    6.000000      270.000000  
75%             61.000000         0.760000    7.000000      294.000000  
max            108.000000        32.000000    8.000000      354.000000  

[8 rows x 21 columns]

In [107]:
Weather_df['Events'].describe()

count      204
unique       9
top       Rain
freq       136
Name: Events, dtype: object

In [108]:
Weather_df['Events']

0      Rain
1       NaN
2       NaN
3       Fog
4       NaN
       ... 
360     NaN
361    Rain
362    Rain
363     Fog
364     NaN
Name: Events, Length: 365, dtype: object

'Events' 카테고리에서 값이 입력되어 있지 않은 항목에 'Sunny'값을 채워넣기

In [109]:
Weather_df['Events']=Weather_df['Events'].fillna('Sunny')

In [110]:
Weather_df

CET  Max TemperatureC  Mean TemperatureC  Min TemperatureC  \
0    2013-01-01                12                  9                 6   
1    2013-01-02                 9                  7                 4   
2    2013-01-03                 8                  4                 0   
3    2013-01-04                 7                  6                 5   
4    2013-01-05                 7                  6                 5   
..          ...               ...                ...               ...   
360  2013-12-27                15                  9                 2   
361  2013-12-28                11                  8                 5   
362  2013-12-29                 9                  7                 4   
363  2013-12-30                 9                  4                 0   
364  2013-12-31                11                  6                 2   

     Dew PointC  MeanDew PointC  Min DewpointC  Max Humidity  Mean Humidity  \
0             8               7              5            93             86   
1             6               4              2            93             86   
2             4               2             -1           100             87   
3             7               6              4           100             94   
4             6               6              4           100             94   
..          ...             ...            ...           ...            ...   
360           8               4              2            93             74   
361          10               6              3           100             81   
362           5               4              3            87             78   
363           4               2              0           100             83   
364           5               3              0            88             76   

     Min Humidity  ...  Max VisibilityKm  Mean VisibilityKm  Min VisibilitykM  \
0              76  ...                31                 10                 5   
1              71  ...                31                 11                10   
2              69  ...                19                 10                10   
3              83  ...                10                  6                 1   
4              90  ...                11                  9                 2   
..            ...  ...               ...                ...               ...   
360            48  ...                23                 10                10   
361            51  ...                31                 11                 8   
362            57  ...                26                 10                10   
363            51  ...                23                  8                 0   
364            58  ...                31                 11                10   

     Max Wind SpeedKm/h  Mean Wind SpeedKm/h  Max Gust SpeedKm/h  \
0                    26                   14                 NaN   
1                    23                   16                 NaN   
2                    13                    5                 NaN   
3                    10                    5                 NaN   
4                    16                    8                 NaN   
..                  ...                  ...                 ...   
360                  29                   11                 NaN   
361                  35                   23                55.0   
362                  27                   21                 NaN   
363                  16                    6                 NaN   
364                  32                   16                 NaN   

     Precipitationmm  CloudCover  Events  WindDirDegrees  
0               5.08         7.0    Rain             234  
1               0.00         5.0   Sunny             298  
2               0.00         5.0   Sunny             118  
3               0.00         8.0     Fog             292  
4               0.00         8.0   Sunny             306  
..               ...         .

'Events'가 'Sunny'이면 "target_Events"를 1, 아니면 0으로 설정

In [111]:
def Make_target(Events):
    if (Events =='Sunny'):
        return 1
    else:
        return 0

In [112]:
Weather_df["target_Events"]=Weather_df.Events.apply(Make_target)

In [113]:
Weather_df['target_Events']

0      0
1      1
2      1
3      0
4      1
      ..
360    1
361    0
362    0
363    0
364    1
Name: target_Events, Length: 365, dtype: int64

**넘파이 배열로 전환**

'Mean TemperatureC', 'MeanDew PointC', 'Mean Humidity', 'Mean Sea Level PressurehPa', 'Mean VisibilityKm', 'Mean Wind SpeedKm/h' = 5개의 변수 사용

In [114]:
data = Weather_df[['Mean TemperatureC','MeanDew PointC', 'Mean Humidity', 'Mean Sea Level PressurehPa',
                   'Mean VisibilityKm', 'Mean Wind SpeedKm/h'  ]].to_numpy()
target = Weather_df['target_Events'].to_numpy()

**사이킷런으로 훈련 세트 / 테스트 세트 나누기**

In [115]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size = 0.2, random_state = 42)

In [116]:
print(train_input.shape, test_input.shape)

(292, 6) (73, 6)


In [117]:
print(train_target.shape, test_target.shape)

(292,) (73,)


**랜덤 포레스트(Random Forest)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [118]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.756750438340152


랜덤 포레스트 모델의 특성 중요도

In [119]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.15448573 0.12624572 0.32930233 0.18274249 0.09527421 0.11194953]


각 결정 트리의 OOB 점수 평균

In [120]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.7465753424657534


**엑스트라 트리(Extra Tree)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [121]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.7531852717708942


엑스트라 트리 모델의 특성 중요도

In [122]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.14811579 0.12412933 0.33074104 0.17202232 0.10191517 0.12307635]


**그레이디언트 부스팅(Gradient Boosting)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [123]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9820292725872125 0.7534774985388661


In [124]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.757042665108124


그레이디언트 부스팅 모델의 특성 중요도

In [125]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.08889272 0.06995996 0.45719776 0.22738088 0.07500765 0.08156103]


**히스토그램 기반 그레이디언트 부스팅(Histogram-Based Gradient Boosting)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [126]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9760206888962253 0.7738164815897136


> 과대 적합을 잘 억제하면서 그레이디언트 부스팅보다 더 높은 성능임을 알 수 있다.

히스토그램 기반 그레이디언트 부스팅 모델의 훈련 세트에서 특성 중요도 

In [127]:
from sklearn.inspection import permutation_importance
hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, 
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.06335616 0.04349315 0.33321918 0.14554795 0.09486301 0.09554795]


히스토그램 기반 그레이디언트 부스팅 모델의 테스트 세트에서 특성 중요도

In [128]:
result = permutation_importance(hgb, test_input, test_target, n_repeats=10, 
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[-0.01232877 -0.00547945  0.14520548  0.05205479  0.02465753  0.01780822]


In [129]:
hgb.score(test_input, test_target)

0.7671232876712328

XGBoost를 사용하여 교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [130]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9340779868676865 0.7671537112799532


LightGBM을 사용하여 교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [131]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9743039506988005 0.770426651081239


각 모델의 점수를 보았을 때 전체적으로 과대적합이 발생하여 아쉬운 성능을 보여주는 것을 확인할 수 있다.


1.   최적의 변수를 찾기 위해 csv파일에서 **NaN값이 없는 모든 변수**를 사용하여 앙상블 학습을 실시한다.

  > Max, Mean, Min값이 모두 존재하는 변수의 경우에는 효율성을 위해 Mean값만 사용



2.   4개의 모델에서 출력된 특성 중요도를 보고 각 모델 별 **중요도가 높은 상위 4개의 변수를 선정**하여 결과를 확인하고자 한다.




**넘파이 배열로 전환**

'Mean TemperatureC', 'MeanDew PointC', 'Mean Humidity', 'Mean Sea Level PressurehPa', 'Mean VisibilityKm', 'Mean Wind SpeedKm/h', 'Precipitationmm', 'WindDirDegrees'
= 8개의 변수(모든 변수) 사용

In [132]:
data = Weather_df[['Mean TemperatureC','MeanDew PointC', 'Mean Humidity', 'Mean Sea Level PressurehPa',
                   'Mean VisibilityKm', 'Mean Wind SpeedKm/h', 'Precipitationmm', 'WindDirDegrees']].to_numpy()
target = Weather_df['target_Events'].to_numpy()

**사이킷런으로 훈련 세트 / 테스트 세트 나누기**

In [133]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size = 0.2, random_state = 42)

In [134]:
print(train_input.shape, test_input.shape)

(292, 8) (73, 8)


In [135]:
print(train_target.shape, test_target.shape)

(292,) (73,)


**랜덤 포레스트(Random Forest)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [136]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8560490940970192


랜덤 포레스트 모델의 특성 중요도

In [137]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.08045219 0.07754723 0.2318745  0.10893472 0.07168635 0.08047321
 0.23283855 0.11619326]




> **중요도 상위 4개의 변수**


1.   'Precipitationmm'

2.   'Mean Humidity'

3.   'WindDirDegrees'

4.   'Mean Sea Level PressurehPa'





각 결정 트리의 OOB 점수 평균

In [138]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8287671232876712


**엑스트라 트리(Extra Tree)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [139]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8286966686148451


엑스트라 트리 모델의 특성 중요도

In [140]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.09478452 0.08070974 0.23640909 0.10767853 0.08344051 0.08578909
 0.18761347 0.12357506]




> **중요도 상위 4개의 변수**


1.   'Mean Humidity'

2.   'Precipitationmm'

3.   'WindDirDegrees'

4.   'Mean Sea Level PressurehPa'





**그레이디언트 부스팅(Gradient Boosting)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [141]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9897252485235318 0.8458211572180012


In [142]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8149620105201636


그레이디언트 부스팅 모델의 특성 중요도

In [143]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.02877853 0.04324103 0.11860877 0.08376268 0.09524348 0.07359019
 0.47864404 0.07813128]




> **중요도 상위 4개의 변수**


1.   'Mean Humidity'

2.   'Mean VisibilityKm'

3.   'Mean Sea Level PressurehPa'

4.   'WindDirDegrees'





**히스토그램 기반 그레이디언트 부스팅(Histogram-Based Gradient Boosting)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [144]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9948571218957486 0.8392168322618352


> 과대 적합을 잘 억제하면서 그레이디언트 부스팅보다 더 높은 성능임을 알 수 있다.

히스토그램 기반 그레이디언트 부스팅 모델의 훈련 세트에서 특성 중요도

In [145]:
from sklearn.inspection import permutation_importance
hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, 
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.02020548 0.02705479 0.12465753 0.05171233 0.07636986 0.0510274
 0.21575342 0.09349315]


히스토그램 기반 그레이디언트 부스팅 모델의 테스트 세트에서 특성 중요도

In [146]:
result = permutation_importance(hgb, test_input, test_target, n_repeats=10, 
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[ 0.00273973 -0.00273973  0.03424658 -0.01917808  0.02465753  0.00136986
  0.09315068 -0.0109589 ]




> **중요도 상위 4개의 변수**


1.   'Precipitationmm’

2.   'Mean Humidity'

3.   'Mean VisibilityKm'

* 3등과 4등 변수의 중요도 차이가 너무 크기 때문에 4등 변수는 제외시켰다.





In [147]:
hgb.score(test_input, test_target)

0.7945205479452054

XGBoost를 사용하여 교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [148]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9674663438611937 0.8630625365283461


LightGBM을 사용하여 교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [149]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.997432229191886 0.8289304500292227


**상위 1등부터 4등까지 각 모델에서 변수를 추출한 결과**


*   'Mean TemperatureC'

*   'MeanDew PointC'

*   'Mean Humidity' 
>  Random, Extra, Gradient, Histogram

*   'Mean Sea Level PressurehPa'
>  Random, Extra, Gradient

*   'Mean VisibilityKm'
>  Gradient, Histogram

*   'Mean Wind SpeedKm/h'

*   'Precipitationmm'
>  Random, Extra, Histogram

*   'WindDirDegrees'
>  Random, Extra, Gradient



# 최적의 변수 설정
어떠한 모델에서도 상위 4개의 중요도에 포함되지 못한 'Mean TemperatureC', 'MeanDew PointC', 'Mean Wind SpeedKm/h'를 제외하고 **'Mean Humidity', 'Mean Sea Level PressurehPa', 'Mean VisibilityKm', 'Precipitationmm', 'WindDirDegrees' 5개의 변수**로 설정하여 검증 과정을 거친다.

**넘파이 배열로 전환**

위에서 설정한 5개의 최적의 변수 사용

In [150]:
data = Weather_df[['Mean Humidity', 'Mean Sea Level PressurehPa',
                   'Mean VisibilityKm', 'Precipitationmm', 'WindDirDegrees']].to_numpy()
target = Weather_df['target_Events'].to_numpy()

**사이킷런으로 훈련 세트 / 테스트 세트 나누기**

In [151]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size = 0.2, random_state = 42)

In [152]:
print(train_input.shape, test_input.shape)

(292, 5) (73, 5)


In [153]:
print(train_target.shape, test_target.shape)

(292,) (73,)


**랜덤 포레스트(Random Forest)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [154]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8423728813559321


랜덤 포레스트 모델의 특성 중요도

In [155]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.26429003 0.15413681 0.10138958 0.30505463 0.17512895]




> 모든 변수들이 비교적 고르게 사용된 것을 알 수 있다.



각 결정 트리의 OOB 점수 평균

In [156]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8287671232876712


**엑스트라 트리(Extra Tree)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [157]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8185271770894215


엑스트라 트리 모델의 특성 중요도

In [158]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.32106598 0.16795117 0.10589685 0.2156617  0.18942431]


**그레이디언트 부스팅(Gradient Boosting)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [159]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9888558746927846 0.8353594389246055


In [160]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8355347749853888


그레이디언트 부스팅 모델의 특성 중요도

In [161]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.16424006 0.12482228 0.10386099 0.48079673 0.12627994]


**히스토그램 기반 그레이디언트 부스팅(Histogram-Based Gradient Boosting)**

교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [162]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9820256043432009 0.8459964932787842


> 과대 적합을 잘 억제하면서 그레이디언트 부스팅보다 더 높은 성능임을 알 수 있다.

히스토그램 기반 그레이디언트 부스팅 모델의 훈련 세트에서 특성 중요도

In [163]:
from sklearn.inspection import permutation_importance
hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, 
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.15719178 0.10753425 0.08527397 0.20034247 0.12054795]


히스토그램 기반 그레이디언트 부스팅 모델의 테스트 세트에서 특성 중요도

In [164]:
result = permutation_importance(hgb, test_input, test_target, n_repeats=10, 
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.03150685 0.04931507 0.00547945 0.05342466 0.04520548]


In [165]:
hgb.score(test_input, test_target)

0.821917808219178

XGBoost를 사용하여 교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [166]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9503539855471187 0.8561075394506137


LightGBM을 사용하여 교차 검증 점수 출력(훈련 세트와 검증 세트 점수 비교)

In [167]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, 
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9786031326803858 0.8358270017533606


# 결과 분석
랜덤 포레스트 모델과 엑스트라 트리 모델의 점수는 최적의 변수를 사용한 결과 점수가 모든 변수를 사용한 결과 점수보다 아주 미세하게 낮다. 하지만 그레이디언트 부스팅 모델의 기본 점수는 미세하게 낮지만 학습률을 증가시키고 트리의 개수를 늘렸을 때는 전체 변수를 사용한 결과보다 더 높은 것을 확인할 수 있다. 또한 히스토그램 기반 그레이디언트 부스팅의 결과는 대체로 최적의 변수를 사용한 결과의 점수가 더 높은 것을 알 수 있다.
# 결론
이상적인 경우 최대한 많은 데이터를 활용하고 최대한 많은 변수를 활용하면 점수값이 높을 것이다. 하지만 많은 데이터, 많은 변수를 사용할 수록 최적의 분할을 찾거나 결과값을 도출해내는데 많은 시간이 필요하기 때문에 **적은 변수로 높은 성능을 보이는 것이 가장 적절**하다고 볼 수 있다.


> 'Mean Humidity', 'Mean Sea Level PressurehPa', 'Mean VisibilityKm', 'Precipitationmm', 'WindDirDegrees' 5개의 변수가 최적의 변수

